select
 'PF_V3_HEALTHCHECK' as status,
 (select min(sector_cutover_date) from public.analytics_settings) as data_corte_v3,
 (select count(*) from public.organizations) as empresas,
 (select count(*) from public.units) as unidades,
 (select count(*) from public.memberships where active) as usuarios_ativos,
 (select count(*) from public.proteins where active) as proteinas_ativas,
 (select count(*) from public.menu_items where active) as itens_ativos,
 (select count(*) from public.menu_items where active and sales_sector='SUSHI_BAR') as itens_sushi_bar,
 (select count(*) from public.menu_items where active and sales_sector='POKE') as itens_poke,
 (select count(*) from public.menu_items where active and sales_sector='KITCHEN') as itens_cozinha,
 (select count(*) from public.menu_items where active and sector_review_required) as itens_revisar_setor,
 (select count(*) from public.menu_items where sector_source='MANUAL') as setores_ajustados_manualmente,
 (select count(*) from public.receipts) as recebimentos_herdados,
 (select count(*) from public.processing_batches) as beneficiamentos_herdados,
 (select count(*) from public.inventory_counts) as inventarios_herdados,
 (select count(*) from public.sales_lines) as linhas_xml_herdadas,
 to_regprocedure('public.pf_upsert_menu_item_v3(uuid,text,text,text,text,uuid,numeric,text,text,text)') is not null as rpc_item_v3_ok,
 to_regprocedure('public.pf_upsert_menu_component_v3(uuid,uuid,numeric,text,text,text)') is not null as rpc_ficha_v3_ok;
